version: 1.0.{build}
branches:
  only:
  - main
#  - develop
  
# Test against this version of Node.js
environment:
  nodejs_version: "20"
  angular_version: "17"
  
build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - npm install -g @angular/cli@$env:angular_version
  - npm install --force

before_build:
  - node --version
  - npm --version
#  - ng test --watch false --single-run true
build_script:
# Publish ng-auth
  - cd projects/ng-auth && npm version patch && cd ../..
  - npm run build-auth
  - cd dist/ng-auth && npm publish
# Publish ng-components
  - cd projects/ng-components && npm version patch && cd ../..
  - npm run build-components
  - npm run postbuild-components
  - cd dist/ng-components && npm publish
 
artifacts:
- path: dist/ng-auth
  name: ng-auth
- path: dist/ng-components
  name: ng-components

#deploy:
#- provider: Environment
#  name: Core.Web (STAGE)
#  on:
#    branch: stage

notifications:
- provider: Email
  to:
  - itsenes@indice.gr
  - d.karkanas@indice.gr
  - e.travlos@indice.gr
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
