name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          npm i --package-lock-only
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          check-latest: true
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: |
          npm install
          npm run build-auth
          npm run build-config
          npm run build-components

      - run: |
          npm run publish-auth
          npm run publish-config
          npm run publish-components
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
