name: Publish Indice.Angular

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: generate package-lock.json
        run: |
          npm i --package-lock-only

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          check-latest: true
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: npm install
        run: |
          npm install

      - name: npm run build-auth
        run: |
          npm run build-auth

      - name: npm run build-components
        run: |
          npm run build-components

      - name: npm run build-config
        run: |
          npm run build-config

      - name: publish to npm registry
        run: |
          npm run publish-auth
          npm run publish-components
          npm run publish-config
